services:
  expense-tracker:
    image: tylerrichey/expense-tracker:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker-app
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY:-}
    volumes:
      - expense_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:${PORT:-3000}/api/expenses', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - expense-tracker-network

volumes:
  expense_data:
    driver: local

networks:
  expense-tracker-network:
    driver: bridge